# Generated by Django 4.2.1 on 2023-11-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='uploads/')),
                ('organizacion', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('tokens', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='uploads/')),
                ('organizacion', models.CharField(max_length=100)),
            ],
        ),
    ]
