# Generated by Django 4.2.1 on 2023-11-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
    ]
