# Generated by Django 4.2.1 on 2023-11-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_alter_empleado_tokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='imagen',
            new_name='imagen_empleado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='tokens',
            new_name='tokens_empleado',
        ),
        migrations.RenameField(
            model_name='empleador',
            old_name='imagen',
            new_name='imagen_empleador',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='organizacion',
        ),
        migrations.RemoveField(
            model_name='empleador',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='empleador',
            name='organizacion',
        ),
        migrations.AddField(
            model_name='empleado',
            name='cargo_empleado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre_empleado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='organizacion_empleado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='empleador',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='empleador_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='empleador',
            name='nombre_empleador',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='empleador',
            name='organizacion_empleador',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='empleador',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='empleador_user_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='contrasena',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleador',
            name='contrasena',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleador',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
