# Generated by Django 4.2.1 on 2023-11-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
