# Generated by Django 4.2.1 on 2023-11-19 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0006_delete_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre_empleado', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('contrasena', models.CharField(default='', max_length=100)),
                ('imagen_empleado', models.ImageField(upload_to='uploads/')),
                ('organizacion_empleado', models.CharField(default='', max_length=100)),
                ('cargo_empleado', models.CharField(default='', max_length=100)),
                ('tokens_empleado', models.IntegerField(default=0)),
            ],
        ),
    ]
