# Generated by Django 4.2.1 on 2023-11-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_empleado_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleador',
            name='email',
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_usuario',
            field=models.CharField(default='empleado', max_length=100),
        ),
        migrations.AddField(
            model_name='empleador',
            name='tipo_usuario',
            field=models.CharField(default='empleador', max_length=100),
        ),
    ]
