# Generated by Django 4.2.1 on 2023-11-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_empleador_email_empleado_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleador',
            name='contrasena',
        ),
    ]
