# Generated by Django 4.2.1 on 2023-11-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_empleador_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='retos_activos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empleado',
            name='retos_finalizados',
            field=models.IntegerField(default=0),
        ),
    ]
