# Generated by Django 4.2.1 on 2023-11-21 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_reto_estado'),
        ('accounts', '0013_empleado_retos_activos_empleado_retos_finalizados'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetosIniciados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empleado')),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.reto')),
            ],
        ),
    ]
