# Generated by Django 4.2.1 on 2023-11-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_retosfinalizados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retosfinalizados',
            old_name='fecha_finalización',
            new_name='fecha_finalizacion',
        ),
    ]
