# Generated by Django 4.2.1 on 2023-11-03 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='uploads/')),
                ('fecha_publicacion', models.DateField(default=datetime.date.today)),
                ('fecha_vencimiento', models.DateField(default=datetime.date.today)),
                ('nombre_insignia', models.CharField(max_length=100)),
                ('categoria_insignia', models.CharField(choices=[('Comunicación efectiva', 'Comunicación efectiva'), ('Trabajo en equipo', 'Trabajo en equipo'), ('Resolución de conflictos', 'Resolución de conflictos'), ('Pensamiento crítico', 'Pensamiento crítico'), ('Creatividad', 'Creatividad'), ('Adaptabilidad', 'Adaptabilidad'), ('Gestión del tiempo', 'Gestión del tiempo'), ('Liderazgo', 'Liderazgo'), ('Empatía', 'Empatía'), ('Habilidades de presentación', 'Habilidades de presentación'), ('Toma de decisiones', 'Toma de decisiones'), ('Escucha activa', 'Escucha activa'), ('Colaboración', 'Colaboración'), ('Autoconfianza', 'Autoconfianza'), ('Resiliencia', 'Resiliencia'), ('Pensamiento analítico', 'Pensamiento analítico'), ('Capacidad de negociación', 'Capacidad de negociación'), ('Habilidades interpersonales', 'Habilidades interpersonales'), ('Gestión del estrés', 'Gestión del estrés'), ('Planificación y organización', 'Planificación y organización')], default='', max_length=100)),
                ('tokens', models.IntegerField()),
                ('limite_participantes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=6)),
                ('cantidad_ganadores', models.IntegerField()),
            ],
        ),
    ]
