# Generated by Django 4.2.1 on 2023-11-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_reto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reto',
            name='estado',
            field=models.CharField(choices=[('INICIADO', 'INICIADO'), ('FINALIZADO', 'FINALIZADO')], default='INICIADO', max_length=10),
        ),
    ]
