# Generated by Django 4.2.6 on 2023-11-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recompensa', '0002_remove_recompensa_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='Logo/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='recompensa',
            name='description',
        ),
        migrations.AddField(
            model_name='recompensa',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='image',
            field=models.ImageField(upload_to='Recompensa/RecompensasImages'),
        ),
    ]
