# Generated by Django 4.2.6 on 2023-11-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recompensa', '0005_remove_recompensa_image_recompensa_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recompensa',
            old_name='title',
            new_name='nombre',
        ),
    ]
