# Generated by Django 4.2.6 on 2023-11-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recompensa', '0006_rename_title_recompensa_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='recompensa',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
