# Generated by Django 4.2.4 on 2023-11-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insignia',
            name='Imagen',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
