# Generated by Django 4.2.4 on 2023-11-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_alter_insignia_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insignia',
            name='Habilidades',
            field=models.CharField(choices=[('Comunicación efectiva', 'Comunicación efectiva'), ('Trabajo en equipo', 'Trabajo en equipo'), ('Resolución de conflictos', 'Resolución de conflictos'), ('Pensamiento crítico', 'Pensamiento crítico'), ('Creatividad', 'Creatividad'), ('Adaptabilidad', 'Adaptabilidad'), ('Gestión del tiempo', 'Gestión del tiempo'), ('Liderazgo', 'Liderazgo'), ('Empatía', 'Empatía'), ('Habilidades de presentación', 'Habilidades de presentación'), ('Toma de decisiones', 'Toma de decisiones'), ('Escucha activa', 'Escucha activa'), ('Colaboración', 'Colaboración'), ('Autoconfianza', 'Autoconfianza'), ('Resiliencia', 'Resiliencia'), ('Pensamiento analítico', 'Pensamiento analítico'), ('Capacidad de negociación', 'Capacidad de negociación'), ('Habilidades interpersonales', 'Habilidades interpersonales'), ('Gestión del estrés', 'Gestión del estrés'), ('Planificación y organización', 'Planificación y organización')], default='', max_length=100),
        ),
    ]
