# Generated by Django 4.2.4 on 2023-11-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_alter_insignia_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibir_insignia',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
